In [6]:
import pandas as pd

#### Data Cleaning

In [10]:
data = {
    "Name": ["Anshu", "Rahul", None, "Neha"],
    "Age": [21, None, 20, None],
    "Department": ["IT", "HR", "Finance", None],
    "Salary": [50000, 45000, None, 52000]
}

In [11]:
df = pd.DataFrame(data)
df

    Name   Age Department   Salary
0  Anshu  21.0         IT  50000.0
1  Rahul   NaN         HR  45000.0
2   None  20.0    Finance      NaN
3   Neha   NaN       None  52000.0

In [12]:
df.isnull().sum()

Name          1
Age           2
Department    1
Salary        1
dtype: int64

In [ ]:
df.dropna()     # any row having null value is removed

    Name   Age Department   Salary
0  Anshu  21.0         IT  50000.0

In [15]:
df.dropna(how = "any")  # any row having null value is removed

    Name   Age Department   Salary
0  Anshu  21.0         IT  50000.0

In [ ]:
df.dropna(how = "all")      # jb sbhi row NULL hoga tb remove hoga

    Name   Age Department   Salary
0  Anshu  21.0         IT  50000.0
1  Rahul   NaN         HR  45000.0
2   None  20.0    Finance      NaN
3   Neha   NaN       None  52000.0

In [ ]:
df.fillna(0)    # fill null value with 0

    Name   Age Department   Salary
0  Anshu  21.0         IT  50000.0
1  Rahul   0.0         HR  45000.0
2      0  20.0    Finance      0.0
3   Neha   0.0          0  52000.0

In [18]:
# replace it with mean value
df["Age"].fillna(df["Age"].mean())

0    21.0
1    20.5
2    20.0
3    20.5
Name: Age, dtype: float64

In [19]:
df["Salary"].fillna(df["Salary"].median())

0    50000.0
1    45000.0
2    50000.0
3    52000.0
Name: Salary, dtype: float64