In [2]:
import pandas as pd

In [4]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
s.dtype

dtype('int64')

In [6]:
s.values

array([10, 20, 30, 40, 50])

In [7]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [9]:
s.name = "numbers"

In [10]:
s

0    10
1    20
2    30
3    40
4    50
Name: numbers, dtype: int64

In [11]:
# indexing

s[0]

np.int64(10)

In [12]:
s[0:2]

0    10
1    20
Name: numbers, dtype: int64

In [13]:
s[2:4]

2    30
3    40
Name: numbers, dtype: int64

In [ ]:
# iloc => location based indexing

s.iloc[3]   # value at index 3

np.int64(40)

In [17]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: numbers, dtype: int64

In [25]:
s.name = "calories"

In [26]:
index = ["apples", "banana", "grapes", "orange", "strawberry"]

In [27]:
s.index = index
s

apples        10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [28]:
s.iloc[3]

np.int64(40)

In [29]:
# loc => label based indexing
s.loc["grapes"]

np.int64(30)

In [30]:
# In label based indexing ur start as well as stop value both are included in the output

s["banana":"grapes"]

banana    20
grapes    30
Name: calories, dtype: int64

In [31]:
fruit_protein = {
    "Avocado": 2.0,
    "Guava": 2.6,
    "BlackBerry":2.0,
    "Orange": 0.9,
    "Banana":1.1,
    "Apples": 0.3
}

In [35]:
s2 = pd.Series(fruit_protein, name="protein")
s2

Avocado       2.0
Guava         2.6
BlackBerry    2.0
Orange        0.9
Banana        1.1
Apples        0.3
Name: protein, dtype: float64

In [36]:
# Conditional Selection

s2>1

Avocado        True
Guava          True
BlackBerry     True
Orange        False
Banana         True
Apples        False
Name: protein, dtype: bool

In [37]:
s2[s2>1]

Avocado       2.0
Guava         2.6
BlackBerry    2.0
Banana        1.1
Name: protein, dtype: float64

In [38]:
# logical operator (not, and, or)

In [41]:
# modifying the Series
s2["Apples"] = 5.2

#### Data Frame

In [42]:
data = {
    "Name": ["Anshu", "Rahul", "Priya", "Neha"],
    "Age": [21, 22, 20, 23],
    "Department": ["IT", "HR", "Finance", "Marketing"],
    "Salary": [50000, 45000, 48000, 52000]
}

In [43]:
data

{'Name': ['Anshu', 'Rahul', 'Priya', 'Neha'],
 'Age': [21, 22, 20, 23],
 'Department': ['IT', 'HR', 'Finance', 'Marketing'],
 'Salary': [50000, 45000, 48000, 52000]}

In [45]:
df = pd.DataFrame(data)
df

    Name  Age Department  Salary
0  Anshu   21         IT   50000
1  Rahul   22         HR   45000
2  Priya   20    Finance   48000
3   Neha   23  Marketing   52000

In [46]:
df.head(2)

    Name  Age Department  Salary
0  Anshu   21         IT   50000
1  Rahul   22         HR   45000

In [ ]:
df.tail(2)      # last 2 rows

    Name  Age Department  Salary
2  Priya   20    Finance   48000
3   Neha   23  Marketing   52000

In [49]:
# loc and iloc

df.iloc[1:3]

    Name  Age Department  Salary
1  Rahul   22         HR   45000
2  Priya   20    Finance   48000

In [51]:
df.loc[1:2, ["Age", "Department"]]

   Age Department
1   22         HR
2   20    Finance

In [54]:
df["Age"]

0    21
1    22
2    20
3    23
Name: Age, dtype: int64

In [55]:
df[["Age", "Department"]]

   Age Department
0   21         IT
1   22         HR
2   20    Finance
3   23  Marketing

In [ ]:
df.drop("Age", axis=1)      # axis=1 mtlb pura column gone

    Name Department  Salary
0  Anshu         IT   50000
1  Rahul         HR   45000
2  Priya    Finance   48000
3   Neha  Marketing   52000

In [57]:
df

    Name  Age Department  Salary
0  Anshu   21         IT   50000
1  Rahul   22         HR   45000
2  Priya   20    Finance   48000
3   Neha   23  Marketing   52000

In [58]:
df.shape

(4, 4)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      object
 1   Age         4 non-null      int64
 2   Department  4 non-null      object
 3   Salary      4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [60]:
# BroadCasting

df["Salary"] = df["Salary"]+100

In [61]:
df["Salary"]

0    50100
1    45100
2    48100
3    52100
Name: Salary, dtype: int64

In [62]:
# renaming columns:

df.rename(columns = {"Department": "Dept"}, inplace = True)

In [63]:
df

    Name  Age       Dept  Salary
0  Anshu   21         IT   50100
1  Rahul   22         HR   45100
2  Priya   20    Finance   48100
3   Neha   23  Marketing   52100

In [64]:
df["Salary"].unique()

array([50100, 45100, 48100, 52100])

In [65]:
df["Dept"].value_counts()

Dept
IT           1
HR           1
Finance      1
Marketing    1
Name: count, dtype: int64

In [68]:
df["Promoted Salary"] = df["Salary"] * 10
df

    Name  Age       Dept  Salary  Promoted Salary
0  Anshu   21         IT   50100           501000
1  Rahul   22         HR   45100           451000
2  Priya   20    Finance   48100           481000
3   Neha   23  Marketing   52100           521000

In [69]:
df

    Name  Age       Dept  Salary  Promoted Salary
0  Anshu   21         IT   50100           501000
1  Rahul   22         HR   45100           451000
2  Priya   20    Finance   48100           481000
3   Neha   23  Marketing   52100           521000

#### Data Cleaning

In [71]:
df.isnull().sum()

Name               0
Age                0
Dept               0
Salary             0
Promoted Salary    0
dtype: int64

In [72]:
data = {
    "Name": ["Anshu", "Rahul", "Priya", "Neha"],
    "Age": [21, 22, 20, 23],
    "Department": ["IT", "HR", "Finance", "Marketing"],
    "Salary": [50000, 45000, 48000, 52000]
}

In [73]:
df

    Name  Age       Dept  Salary  Promoted Salary
0  Anshu   21         IT   50100           501000
1  Rahul   22         HR   45100           451000
2  Priya   20    Finance   48100           481000
3   Neha   23  Marketing   52100           521000

In [74]:
df.isnull().sum()

Name               0
Age                0
Dept               0
Salary             0
Promoted Salary    0
dtype: int64